version: '3.2'

services:

  frontend:
    build: frontend
    container_name: apple_frontend
    ports:
      - 20080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app

  backend:
    build: backend
    container_name: apple_backend
    ports:
      - 21080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app

  apple-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: apple_phpmyadmin
    ports:
      - target: 80
        published: 8090
        protocol: tcp
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    env_file:
      - .env
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD:'yes'
